title: Bonsai @ Inercia 2020
description: Bonsai introduction at Inercia Demo Party 2020.
google_analytics:
theme: minima
baseurl: "/inercia-2020"

twitter_username: bonsai_rx
github_username:  bonsai-rx

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"

collections:
  # Ideally we would use collections for slides but this
  # breaks reveal.js markdown processing because of issue:
  # https://github.com/jekyll/jekyll/issues/6209
  # slides:
  #   output: true
  #   permalink: /:collection/:path/
